
steps:
  # Build the Docker image using the Docker Cloud Builder
  - name: 'gcr.io/cloud-builders/docker'
  #args
    args: ['build', '-t', 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:latest', '-t', 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:$COMMIT_SHA', '.']

  # Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:$COMMIT_SHA']

  # Deploy the container to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'midterm'
      - '--image'
      - 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Use '--no-allow-unauthenticated' if you don't want to allow unauthenticated access

images:
  - 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:latest'
  - 'us-central1-docker.pkg.dev/midterm-devops/betty-repository/midterm:$COMMIT_SHA'


 
